USE [DreamCareer]
GO

/****** Object:  Table [dbo].[Tag]    Script Date: 4/26/2016 6:19:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Tag](
	[TagID] [int] IDENTITY(1,1) NOT NULL,
	[PositionID] [int] NULL,
	[TagWord] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TagID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Tag]  WITH CHECK ADD  CONSTRAINT [FK__Tag__PositionID__3A81B327] FOREIGN KEY([PositionID])
REFERENCES [dbo].[Position] ([PositionID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Tag] CHECK CONSTRAINT [FK__Tag__PositionID__3A81B327]
GO

