USE [master]
GO

/****** Object:  Database [DreamCareer]    Script Date: 4/23/2016 4:26:25 PM ******/
CREATE DATABASE [DreamCareer]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DreamCareer', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.TITAN\MSSQL\DATA\DreamCareer.mdf' , SIZE = 102400KB , MAXSIZE = 204800KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'DreamCareer_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.TITAN\MSSQL\DATA\DreamCareer_log.ldf' , SIZE = 20480KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DreamCareer] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DreamCareer].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DreamCareer] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DreamCareer] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DreamCareer] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DreamCareer] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DreamCareer] SET ARITHABORT OFF 
GO

ALTER DATABASE [DreamCareer] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DreamCareer] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DreamCareer] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DreamCareer] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DreamCareer] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DreamCareer] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DreamCareer] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DreamCareer] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DreamCareer] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DreamCareer] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DreamCareer] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DreamCareer] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DreamCareer] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DreamCareer] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DreamCareer] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DreamCareer] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DreamCareer] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DreamCareer] SET RECOVERY FULL 
GO

ALTER DATABASE [DreamCareer] SET  MULTI_USER 
GO

ALTER DATABASE [DreamCareer] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DreamCareer] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DreamCareer] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DreamCareer] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DreamCareer] SET  READ_WRITE 
GO

