
USE DreamCareer
GO

CREATE TABLE CompanyHasTag
(
	TagID int,
	CompanyID int,

	FOREIGN KEY (TagID) REFERENCES Tag(TagID)
	ON DELETE CASCADE
	ON UPDATE CASCADE,

	FOREIGN KEY (CompanyID) REFERENCES Company(CompanyID)
	ON DELETE CASCADE
	ON UPDATE CASCADE
)